### ISSUE TITLE
WIKI - TEMPLATE() ExportJson

### ISSUE THREAD

**Issue by ririfonfon** [hossimo/GMA3Plugins#16]
in your exemple he have a mistake on options

local filename = "ExportFile.JSON"
local drives = Root().Temp.DriveCollect
local sep = GetPathSeparator()
local selectedDrive -- users selected drive
local options       -- popup options **wrong**
local options = {}       -- popup options **good**

**Comment by hossimo** [comment]
Right you are! I updated 
https://github.com/hossimo/GMA3Plugins/wiki/ExportJson
https://github.com/hossimo/GMA3Plugins/wiki/ExportCSV


Thanks.

**Comment by hossimo** [comment]
Also, I can add you as a contributor if you wanted to make wiki edits.

**Comment by ririfonfon** [comment]
Yes with pleasure

**Comment by hossimo** [comment]
There you go.
