### ISSUE TITLE
Copy Screenshots 1.0.0.3 not work in 1.1.4.2

### ISSUE THREAD

**Issue by ririfonfon** [hossimo/GMA3Plugins#17]
all image sizes are only 1k

**Comment by hossimo** [comment]
Interesting, is this onPC? I originally just tested it on the console and that worked, but just tested on Windows and it doesn't, looks like it's only copying the header.

Should be a simple fix.

**Comment by hossimo** [comment]
d4c83c0030a1b91e6f9e6647501a934837359422 should fix the problem.

Take a look at [this](https://raw.githubusercontent.com/hossimo/GMA3Plugins/bugfix-CopyScreenShots/grandMA3/shared/resource/lib_plugins/Copy%20Screenshots.lua)

To see if it fixes it for you.

If it does I'll merge it in and make a new version.

**Comment by ririfonfon** [comment]
OK it's work
I upgraded your plugin, because I found it a bit intrusive.
With the number of versions of the GMA3 which increases the plug copied in too many directories.

if you can test my version and do some feedback. on console it would be cool (because with the covid I don't have access to it).

[https://github.com/ririfonfon/GMA3Plugins/tree/master/grandMA3/shared/resource/lib_plugins/Export_Screen_Shoot](url)

**Comment by hossimo** [comment]
Glad it worked. I'll merge it soon.

Also yours works on my console as well, however I did have to edit the xml. I made an [issue](https://github.com/ririfonfon/GMA3Plugins/issues/1)

**Comment by ririfonfon** [comment]
ok cool what was the problem with xml
