### ISSUE TITLE
ver 1.2.0.2

### ISSUE THREAD

**Issue by ririfonfon** [hossimo/GMA3Plugins#19]
hello hoss,

we have some new fonction ::
"GetPresetData","GetTopOverlay","SelectionNotifyObject", "SetColor","ShowSettings"

and remove ::
"SelectedGelNr","TestClickGesture","TestColumnResize","TestCombinedSelection","TestGridKeepScrollCellVisible","TestPanScroll"

see you

**Comment by hossimo** [comment]
SelectionNotifyObject was already there and I did not have any of the ones to remove.

Thanks so much for finding these!

Fixed it [here](https://github.com/hossimo/GMA3Plugins/wiki/Home/_compare/d8b8699939cb4eedae640546fde5592c4e049193...a2ab4b95359053bdce3b1d659c77f7aa823408c1)
