### ISSUE TITLE
Importing issue

### ISSUE THREAD

**Issue by TomyVertigo** [hossimo/GMA3Plugins#2]
Hello,

I have a problem importing this plug-in.

![image](https://user-images.githubusercontent.com/63294196/78667082-a08bb180-78d8-11ea-8d15-9584cdf70ec9.png)

**Comment by hossimo** [comment]
Which Plugin are you having an issue loading? Also how are you downloading the files from? I just tested loading all of the plugins downloaded from both the [Clone or Download](https://github.com/hossimo/GMA3Plugins/archive/master.zip) and [Releases](https://github.com/hossimo/GMA3Plugins/releases) onto a console on V1.1.3.2 and they all loaded correctly. Last I checked they also loaded in 1.0.0.3 correctly as well.

Usually if a plugin fails to load its logged in the Add Window >More >System Monitor. Can you send me any errors you are seeing there.

**Comment by TomyVertigo** [comment]
Thanks mate. I downloaded now with Clone and it works perfectly. 

You are the best! 
Thank you

**Comment by hossimo** [comment]
Ok, Glad it's working.
