### ISSUE TITLE
WIKI - example for coroutine.yield()

### ISSUE THREAD

**Issue by lukas-runge** [hossimo/GMA3Plugins#26]
### Brief:
I haven't fully understood what coroutines do, but I have used coroutine.yield to allow for a "main event loop" type of use case in MA3. So I got the example and it seems like there is a lot of ressources on the topic. But I haven't really fully understood those yet. Maybe it's because I don't have a professional development background. Idk. https://www.tutorialspoint.com/lua/lua_coroutines.htm
❓

### Paramiters:

 Name | Type  | Description | Optional
-- | -- | -- | --
time in seconds | float | duration the current coroutine is suspended for | ❓

### Returns:
❓

### Examples:

```lua
local runsPerSecond = 10

local function mainEventLoop()
  while true do
    Printf('Hello from the dark side!')
    coroutine.yield(1 / runsPerSecond)
  end
end

return mainEventLoop
```

**Comment by hossimo** [comment]
To be honest I thought i had a coroutine.yield() entry in the wiki, I'll definitely add one though.

The interesting thing I have found with coroutines in MA3 is that each plugin seems to already be in a Coroutine, hence not having to create one as you normally would in LUA, C# or Kotlin, There is a fair amount of guessing how it works on the backend so I need to try and be clear on how it works, but I believe a simple example like yours should suffice.

I'll try and and one shortly.

**Comment by hossimo** [comment]
I added https://github.com/hossimo/GMA3Plugins/wiki/coroutine. it is in a slightly different format since it's not an MA API, but we can see how that works.

**Comment by lukas-runge** [comment]
Awesome! @hossimo

Thank you for the new entry in the wiki. I also think it is sufficient for most use cases and we can still add to it as we discover more about coroutine handling in MA3. 👍

Kind regards
@lukas-runge
