### ISSUE TITLE
Changes of Lua API in v1.4.0.2 (WIKI)

### ISSUE THREAD

**Issue by lukas-runge** [hossimo/GMA3Plugins#28]
Happy New Year @hossimo,

i have discovered some changes in the Lua API that should be added to the wiki:

- gone in v1.4.0.2
  - `Execute`
  - `idx`
  - `last`
- added in v1.4.0.2
  - `FindTexture`
  - `LoadStorePreferencesFromProfile`
  - `SaveStorePreferencesToProfile`
  - `SetFilterSettingsTarget`
  - `UnhookMultiple`
- bugs
  - `MultiLanguage` is still present in v1.4.0.2
  - `Set Color` has a typo: `SetColor`

If you add me as contributor I'd be happy to add those changes myself. 😇

Kind regards
@lukas-runge

**Comment by hossimo** [comment]
I haven't done a diff on the versions yet but I have made you a contributor.

Happy New Years!

**Comment by hossimo** [comment]
I haven't thought too much of this yet but I think the removed items should be ~~struck out~~ and if a page exists it should be kept but noted when it was removed.

**Comment by lukas-runge** [comment]
Just added the changes: [🔖 updated functions for v1.4.0.2, Issue #28](https://github.com/hossimo/GMA3Plugins/wiki/Home/_compare/478384cc2d6c4419cfebfa18747c648fd72a6260...b173c176947579f38923e5b57f8d44cafc76a6ca?diff=unified&short_path=355883c#diff-355883cf07556dda17d052752e54eb44edf0104280e7f9c9f33fe04d4648bb17)
Closing issue #28

Kind regards
@lukas-runge
