### ISSUE TITLE
PopupInput()

### ISSUE THREAD

**Issue by kinglevel** [hossimo/GMA3Plugins#30]
Update needed, found on firmware 1.6.1.3.

It seems like PopupInput() has changed its way of handling arguments and parameters.
The example code on the wiki throw errors.

This is the new way of writing it accordingly to the system_test example files:

```
local function myFunction(display_handle)
	local modes = {"test1", "test2"};
	local popup = PopupInput({title="test", caller=display_handle, items=modes})
end
```

Rewritten Option1 example:
```
local function Main(display_handle) -- we need this display_handle
    local titlename = "Select your type of pizza"
    local options = {"Pineapple", "Pepperoni", "Mushroom"}
    local r = PopupInput({title=titlename, caller=display_handle, items=options, "Pepperoni"}) -- defaults to "Pepperoni"
    Printf("result: " .. r .. " is type: " .. type(r)) -- print returned number and type
end
```

**Comment by hossimo** [comment]
Thanks for the update. I actually noticed back in 1.5 when I was writing a plugin for something but hadn't had time to fix the documentation. I'll get to this today.

Thanks for this!

**Comment by hossimo** [comment]
Now I recall why I didn't fix the documentation: the signature does not seem to work as soon as I try adding the `selectedValue` key and there are a lot more keys that I need to figure out.
```
PopupInput(
   {
      title:str,
      caller:handle,
      items:table:{
         {'str'|'int'|'lua'|'handle', name, type-dependent} ...
      },
      selectedValue:str,
      x:int,
      y:int,
      target:handle,
      render_options: {left_icon,number,right_icon},
      useTopLeft:bool,
      properties:{prop:value}
   }): string:value
```

I think I should at least document as much as I can make work.

**Comment by hossimo** [comment]
Fixed. There is still some missing info but the examples should now work.
