### ISSUE TITLE
GetPath 1.8.1.0

### ISSUE THREAD

**Issue by kinglevel** [hossimo/GMA3Plugins#34]
GetPath example page is not correct, 35 is now for example the plugin path.

**Comment by hossimo** [comment]
Thanks for the update.

I've downloaded and installed 1.8 on my desk but I haven't had any time to play with it yet.

I have updated the page with the correct info.

If you are looking for the plugin path you should probably use `GetPath("plugins")` as the numbers will probably change from version to version.

I would like to find all of the string representations, but I haven't had much time to look for a list.

https://github.com/hossimo/GMA3Plugins/wiki/GetPath/_compare/c3e28dbc09937eb02a3855770c65bae79d902baa...70a5c4eeb9abd5453b6cd0a7a6aaf29ce3fc0bc4?diff=unified

Thanks again.
