### ISSUE TITLE
Images in apperance builder

### ISSUE THREAD

**Issue by utombords** [hossimo/GMA3Plugins#39]
It would be quite useful to be able to assign image with appearance builder.

**Comment by hossimo** [comment]
Yes, this does sound like it would be helpful. I assume that you would want to use the same image for a run of the command.

Without having to rewrite to avoid using the MessageBox() I guess I could add a field that you could enter the index or name of an image from the pool.

One issue right now is I currently set the foreground and background to the same color, which could make the image not show up. I guess I could add two more options to omit the foreground or background color and leave it at black.

Is that your use case?

**Comment by utombords** [comment]
Yes, the same image for the whole run is the behavior i would like to expect. 

I have noticed that I want to set both background color and background alpha to a value of zero.
Doing so makes the appearance image fill a layout element all the way to its borders.

But i guess, like you say, a single checkbox to disable background color and alpha would be just fine for this.

**Comment by hossimo** [comment]
I will add this to the plugin but for the moment you can do `Assign Image 3.x At Appearance y Thru z`

where x is the image pool index you want to use for appearances y thru z

**Comment by hossimo** [comment]
Hey there sorry for the long wait; had some other jobs and decided to completely rewrite the UI. 

I added Images as an option as well as alpha and separate fill and outline controls.

https://github.com/hossimo/GMA3Plugins/tree/master/grandMA3/shared/resource/lib_plugins/Appearance%20Builder#appearancebuilder-v16

**Comment by utombords** [comment]
Thanks for this, just tried and it works perfectly.
Really appreciate it.

Henrik

Den tors 30 maj 2024 kl 16:40 skrev Anthony Headley <
***@***.***>:

**Comment by hossimo** [comment]
No worries, I'm glad I did it, got me to learn something new.
